
export const APP_CONSTANTS = {
  INITIAL_BALANCE: 10000,
  CURRENCY_MAX_DIGITS: 11,
  TRANSACTION_COUNT_MIN: 15,
  TRANSACTION_COUNT_MAX: 30,
  INVESTMENT_COUNT_MIN: 10,
  INVESTMENT_COUNT_MAX: 20,
  BREAKPOINTS: {
    MOBILE: 768,
    TABLET: 1024,
    DESKTOP: 1280,
  },
} as const;

